src/Entity/Research.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ResearchRepository")
 */
class Research
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Tag", inversedBy="researches", cascade={"persist"})
     */
    private $tags;

    /**
     * @ORM\Column(type="datetime")
     */
    private $search_date;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Url", mappedBy="research", cascade={"persist"})
     */
    private $urls;

    /**
     * @ORM\Column(type="datetime")
     */
    private $endDate;

    /**
     * @ORM\Column(type="integer")
     */
    private $crawledUrls;

    /**
     * @ORM\Column(type="integer")
     */
    private $availableDomains;

    public function __construct()
    {
        $this->tags = new ArrayCollection();
        $this->urls = new ArrayCollection();
        $this->crawledUrls = 0;
        $this->availableDomains = 0;
        $this->setEndDate(new \DateTime(date('Y-m-d H:i:s')));
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Collection|tag[]
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        if ($this->tags->contains($tag)) {
            $this->tags->removeElement($tag);
        }

        return $this;
    }

    public function getSearchDate(): ?\DateTimeInterface
    {
        return $this->search_date;
    }

    public function setSearchDate(\DateTimeInterface $search_date): self
    {
        $this->search_date = $search_date;

        return $this;
    }

    /**
     * @return Collection|Url[]
     */
    public function getUrls(): Collection
    {
        return $this->urls;
    }
    public function getUrlsLeft(): array
    {
        $urlsLeft = array();
        foreach($this->urls as $url){
            if ($url->getCrawled()==1){
                array_push($urlsLeft, $url);
            }
        }
        return $urlsLeft;
    }

    public function addUrl(Url $url): self
    {
        if (!$this->urls->contains($url)) {
            $this->urls[] = $url;
            $url->addResearch($this);
        }

        return $this;
    }

    public function removeUrl(Url $url): self
    {
        if ($this->urls->contains($url)) {
            $this->urls->removeElement($url);
            $url->removeResearch($this);
        }

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getCrawledUrls(): ?int
    {
        return $this->crawledUrls;
    }

    public function setCrawledUrls(int $crawledUrls): self
    {
        $this->crawledUrls = $crawledUrls;

        return $this;
    }

    public function getAvailableDomains(): ?int
    {
        return $this->availableDomains;
    }

    public function setAvailableDomains(int $availableDomains): self
    {
        $this->availableDomains = $availableDomains;

        return $this;
    }
}

templates/banned.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index{% endblock %}


{% block body %}
    {{ form_start(form) }}
	{{ form_widget(form) }}
	{{ form_end(form) }}
	<div>
	 	<table class="table">
            <thead>
                <tr>
                    <th>
                        Nom de domaine
                    </th>
                </tr>
            </thead>
            <tbody>
				{% for url in banned %}
					<tr><td>{{url.name}}</td></tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/jq-3.2.1/dt-1.10.16/datatables.min.css"/>        
        {% block stylesheets %}{% endblock %}
    	<link rel="stylesheet" href="{{ asset('build/app.css') }}">
    </head>
    
    <body>
		<nav class="navbar navbar-expand-lg navbar-light bg-light">
		  <a class="navbar-brand" href="#">Navbar</a>
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>

		  <div class="collapse navbar-collapse" id="navbarSupportedContent">
		    <ul class="navbar-nav mr-auto">
		      <li class="nav-item">
		        <a class="nav-link" href="{{ path('indexcrawl') }}">Accueil</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link" href="{{ path('domain_index') }}">Domaines</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link" href="{{ path('search_index') }}">Recherches</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link" href="{{ path('tag_index') }}">Tags</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link" href="{{ path('banned_index') }}">Url bannies</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link" href="{{ path('city_index') }}">Villes</a>
		      </li>
		  	</ul>
		      <span  class="navbar-text">
		      	Crédits restants {{credits.actual}}
		      </span>
		  </div>
		</nav>
		<div class="container-fluid">
        	{% block body %}{% endblock %}
    	</div>

 		<script type="text/javascript" src="https://cdn.datatables.net/v/dt/jq-3.2.1/dt-1.10.16/datatables.min.js"></script>
 		<script src="{{ asset('bundles/datatables/js/datatables.js') }}"></script>
        <script src="{{ asset('build/app.js') }}"></script>
        {% block javascripts %}{% endblock %}


    </body>
</html>

templates/cities.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index{% endblock %}


{% block body %}
    {{ form_start(form) }}
	{{ form_widget(form) }}
	{{ form_end(form) }}
	<div>
	 	<table class="table">
            <thead>
                <tr>
                    <th>
                        Ville
                    </th>
                </tr>
            </thead>
            <tbody>
				{% for city in cities %}
					<tr><td>{{city.name}}</td></tr>
				{% endfor %}
			</tbody>
        </table>
    </div>
{% endblock %}

templates/domains.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index{% endblock %}


{% block body %}
    <div class="row">
        <h1>Domaines</h1>
    </div>
    <div class="row">
        <h3>Domaines disponibles : </h3>
    </div>
    <div class="form-group">
        <!-- indentation bizare a cause du textarea -->
        <textarea id="textareaToCopy" class="form-control textareaToCopy">
{% for domain in domains %}{% if domain.dispo == 'Disponible'%}{{domain.domainName}}
{% endif %}{% endfor %}
        </textarea>
        <button class="btn btn-sm btn-primary" id="clipboard"><i class="fas fa-copy"></i></button>
    </div>
    <div>
        {{ form_start(form) }}
        <div class="row">
            <div  class="col">
                <div class="row">
                    <div class="col text-right">
                    {{ form_label(form.TF) }}
                    </div>  
                    <div class="col">
                    {{ form_widget(form.TF) }}
                    {{ form_help(form.TF) }}
                    </div>
                </div>
            </div>
            <div  class="col">
                <div class="row">
                    <div class="col text-right">
                    {{ form_label(form.TM) }}
                    </div>  
                    <div class="col">
                    {{ form_widget(form.TM) }}
                    {{ form_help(form.TM) }}
                    </div>
                </div>
            </div>
            <div  class="col">
                <div class="row">
                    <div class="col text-right">
                    {{ form_label(form.RefIp) }}
                    </div>  
                    <div class="col">
                    {{ form_widget(form.RefIp) }}
                    {{ form_help(form.RefIp) }}
                    </div>
                </div>
            </div>
            <div  class="col">
                {{ form_row(form.save) }}
            </div>
        </div>
        {{ form_end(form) }}
        <table class="table dataTable">
            <thead>
                <tr>
                    <th class="name">Nom de domaine</th>
                    <th class="trustflow">TF</th>
                    <th class="trustmetrics">TM</th>
                    <th class="refip">RefIP</th>
                    <th class="title">Title</th>
                    <th class="language">Language</th>
                    <th class="ttf">TTF</th>
                    <th class="tags">Tags</th>
                    <th class="liens">Liens</th>
                    <th class="achat">Achat</th>
                    <th class="date">Date crawl</th>
                </tr>
            </thead>
            <tbody>

                {% for domain in domains %}
                    {% if domain.dispo == 'Disponible'%}
                        {% include 'list_available_domains.html.twig' %}
                    {% endif %}
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index{% endblock %}

{% block body %}
    <div class="main_recherche">
    	<div class="main_tags">
    		<h1>Tags</h1>
	       	{{ form_start(form_tags) }}
	       	<div class="row">
	            <div class="col mb-3">
	            {{ form_widget(form_tags.keywords) }}
	            
	            </div>  
	        </div>
	        <div class="row">
	            <div class="col-lg-3 col-xs-4">
	            {{ form_widget(form_tags.city) }}
	            </div> 
	            <div class="col-lg-3 col-xs-4">
	            {{ form_widget(form_tags.getUrl) }}
	            </div>   
	        </div>
	       	
			{{ form_end(form_tags) }}
			{% if recupOK is same as (true) %}
				<div class="alert alert-success" role="alert">
					Récuperation des domaines effectuée avec succès
				</div>
			{% elseif recupOK  is same as (false) %}
				<div class="alert alert-danger" role="alert">
					Problème lors de la récuperation des domaines
				</div>
			{% endif %}
		</div>
		<div class="main_urls">
			<h1>Recherche</h1>
		    {{ form_start(form_crawl) }}
			{{ form_widget(form_crawl) }}
			{{ form_end(form_crawl) }}
		</div>
	</div>
	{% for city in cities %}
		<input type="hidden" value="{{city.name}}" class="city">
	{% endfor %}
{% endblock %}
      

templates/list_available_domains.html.twig
<tr>
    <td class="p-1">
        <div class="input-group">
            <span class="d-none">{{domain.domainName}}</span>
            <input type="text" class="domainToCopy" value="{{domain.domainName}}"/>
            <button class="btn btn-sm btn-secondary buttonToCopy" data-clipboard-target="#foo">
                <i class="fas fa-copy"></i>
            </button>
        </div>
    </td>
    <td class="p-1">{{domain.trustFlow}}</td>
    <td class="p-1">{{domain.trustMetrics}}</td>
    <td class="p-1">{{domain.RefIP}}</td>
    <td class="p-1">{{domain.Title}}</td>
    <td class="p-1">{{domain.Language}}</td>
    <td class="p-1"> 
        {% for ttf in domain.getTopicalTrustFlows %}
            {% set topics = ttf.topic|split('/')%}
            <span class="badge badge-{{topics[0]}}">{{ttf.value}} {{ttf.topic}}</span>
        {% endfor %}
    </td>
    <td class="p-1">
        {% for tag in domain.getTags %}
            <span class="badge badge-secondary">{{tag}} </span>
        {% endfor %}
    </td>
    <td class="p-1"> <!-- liens infos-->
        <button type="button" class="btn btn-sm btn-dropdown dropdown-toggle" data-toggle="dropdown">
            Choisir
        </button>
        <div class="dropdown-menu">
            <a class="dropdown-item" href="https://app.seobserver.com/sites/view/{{domain.domainName}}" target="blank">SEO</a>
            <a class="dropdown-item" href="https://web.archive.org/web/*/{{domain.domainName}}" target="blank">WebA</a>
            <a class="dropdown-item" href="http://www.screenshots.com/search/?q={{domain.domainName}}" target="blank">SS</a>
        </div>
    </td>
    <td class="p-1"> <!-- liens achat-->
        <button type="button" class="btn btn-sm btn-dropdown dropdown-toggle" data-toggle="dropdown">
            Choisir
        </button>
        <div class="dropdown-menu">
            <div class="dropdown-header">Lien direct</div>
            <a class="dropdown-item"  href="https://www.namebright.com/{{domain.domainName}}" target="blank">NameBright</a>
            <a class="dropdown-item"  href="https://shop.gandi.net/fr/domain/suggest?search={{domain.domainName}}" target="blank">Gandi</a>
            <a class="dropdown-item"  href="https://cp.espace2001.com/cart.php?a=add&domain=register&query={{domain.domainName}}" target="blank">E2001</a>
            <a class="dropdown-item"  href="https://www.namecheap.com/domains/registration/results.aspx?domain={{domain.domainName}}" target="blank">NameCheap</a>
            <a class="dropdown-item"  href="https://fr.godaddy.com/domains/searchresults.aspx?isc=gofhfhfr08&checkAvail=1&tmskey=ad_dlp_com_fr&domainToCheck={{domain.domainName}}" target="blank">GoDaddy</a>
            <a class="dropdown-item"  href="https://www.ovh.com/fr/order/domain/#/legacy/domain/search?domain={{domain.domainName}}" target="blank">OVH</a>
            <div class="dropdown-header">Lien global</div>
            <a class="dropdown-item"  href="https://internetbs.net/fr/enregistrement-domaines/index.html" target="blank">Internet.bs</a>
            <a class="dropdown-item"  href="https://www.dynadot.com/fr/" target="blank">Dynadot</a>
        </div>
        
    </td>
    <td class="p-1">
        {{domain.creationDate|date('d/m/Y H:i:s')}}
    </td>
</tr>

templates/researches.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index{% endblock %}

{% block body %}
    <div class="recherche">
        <h1>Recherches</h1>
        <table class="table">
            <tr>
                <th>
                    Recherche
                </th>
                <th>
                    Avancement
                </th>
                <th>
                   Url crawlés
                </th>
                <th>
                   Domaines trouvés
                </th>
                <th>
                </th>
            </tr>
            {% for search in researches %}
            <tr>
                <td>
                    <a href="{{ path('search_show', {'id': search.id}) }}">{{search.searchDate|date("d/m/Y H:i") }}</a> 
                    {% for tag in search.tags %}
                        {{tag.name}} 
                    {% endfor %}
                </td>
                <td>{{search.getUrlsLeft()|length}}/{{search.getUrls()|length}}
                    {% if search.getUrls()|length >0 %}
                        ({{(search.getUrlsLeft()|length / search.getUrls()|length *100)|round(1, 'floor')}}%)
                    {% endif %}
                <td>
                    {{search.crawledUrls}}
                </td>
                <td>
                    {{search.availableDomains}}
                </td>
                <td id="search_td_{{search.id}}">
                    {% if search.getUrls()|length != search.getUrlsLeft()|length %}
                        <a class="btn btn-primary btn-sm search_launch" id="launch_crawl_{{search.id}}" onclick="launchCrawl({{search.id}},'{{ path('researchcrawl', {'id': search.id}) }}')">Lancer</a>
                    {% endif %}
                </td>
            <tr>
        {% endfor %}
        </table>
    </div>
{% endblock %}
{% block javascripts %}
    <!-- script ici pour recuperer la variable path -->
<script>
function launchCrawl(id, Path) {
    $('#launch_crawl_'+id).remove();
    $('#search_td_'+id).html('<i class="fas fa-spinner fa-pulse fa-2x"></i>');
    $.ajax({
        type: "POST",
        url: Path,
        async: true,
        data: { },
        success: function () {
            $('#search_td_'+id).html('Terminé');
        }
    });
}</script>
{% endblock %}

templates/search_show.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index{% endblock %}


{% block body %}
    <div class="row">
        <h1>Resultats de la recherche du {{research.searchDate|date("d/m/Y H:i:s")}}</h1>
    </div>
    <div class="row">
        <h2>Mots clés : 
            {% for tag in research.tags %}
                {{tag}} 
            {% endfor %}
        </h2>
    </div>
    <div class="row">
        <h3>Domaines expirés : </h3>
    </div>
    <div class="form_group">
        <!-- indentation bizare a cause du textarea -->
        <textarea id="textareaToCopy" class="form-control textareaToCopy">
{% for url in research.urls %}{% for domain in url.domains %}{% if domain.dispo == 'Disponible'%}{{domain.domainName}}
{% endif %}{% endfor %}{% endfor %}
        </textarea>
        <button id="clipboard"><i class="fas fa-copy"></i></button>
    </div>
    <div>
        <table class="table dataTable">
            <thead>
                <tr>
                    <th class="name">Nom de domaine</th>
                    <th class="trustflow">TF</th>
                    <th class="trustmetrics">TM</th>
                    <th class="refip">RefIP</th>
                    <th class="title">Title</th>
                    <th class="language">Language</th>
                    <th class="ttf">TTF</th>
                    <th class="tags">Tags</th>
                    <th class="liens">Liens</th>
                    <th class="achat">Achat</th>
                    <th class="date">Date crawl</th>
                </tr>
            </thead>
            <tbody>
            {% for url in research.urls %}
                {% for domain in url.domains %}
                    {% if domain.dispo == 'Disponible'%}
                        {% include 'list_available_domains.html.twig' %}
                    {% endif %}
                {% endfor %}
            {% endfor %}
            </tbody>
       </table>
    </div>
    <div>
        <table class="table mt-2">
            <thead>
                <tr>
                    <th>
                        Url crawlée
                    </th>
                </tr>
            </thead>
            <tbody>
            {% for url in research.urls %}
                <tr><td>{{url.address}}</td></tr>
            {% endfor %}
            </tbody>
       </table>
   </div>
{% endblock %}

templates/search_tags.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index{% endblock %}

{% block body %}
    <div class="recherche">
    	<h1>Nouvelle recherche</h1>
       
        <button class="btn btn-secondary btn-sm" type="button" id="addCity">Ajouter les villes</button> 
        <button class="btn btn-secondary btn-sm" type="button" id="generateUrl">Générer url</button> 
        {{ form_start(form) }}
		{{ form_widget(form) }}
		{{ form_end(form) }}
	</div>
	
{% endblock %}
      

templates/tag_show.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index{% endblock %}


{% block body %}
    <div class="row">
        <h1>Resultats pour le tag "{{tag.name}}"</h1>
    </div>
    <div class="row">
        <h3>Domaines expirés : </h3>
    </div>
    <div class="form_group">
        <!-- indentation bizare a cause du textarea -->
        <textarea id="textareaToCopy" class="form-control textareaToCopy">
{% for research in tag.researches %}{% for url in research.urls %}{% for domain in url.domains %}{% if domain.dispo == 'Disponible'%}{{domain.domainName}}
{% endif %}{% endfor %}{% endfor %}{% endfor %}
        </textarea>
        <button id="clipboard"><i class="fas fa-copy"></i></button>
    </div>
    <div>
         <table class="table dataTable">
            <thead>
                <tr>
                    <th class="name">Nom de domaine</th>
                    <th class="trustflow">TF</th>
                    <th class="trustmetrics">TM</th>
                    <th class="refip">RefIP</th>
                    <th class="title">Title</th>
                    <th class="language">Language</th>
                    <th class="ttf">TTF</th>
                    <th class="tags">Tags</th>
                    <th class="liens">Liens</th>
                    <th class="achat">Achat</th>
                    <th class="date">Date crawl</th>
                </tr>
            </thead>
            <tbody>
            {% for research in tag.researches %}
                {% for url in research.urls %}
                    {% for domain in url.domains %}
                        {% if domain.dispo == 'Disponible'%}
                            {% include 'list_available_domains.html.twig' %}
                        {% endif %}
                    {% endfor %}
                {% endfor %}
            {% endfor %}
        </table>
    </div>
{% endblock %}

templates/tags.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index{% endblock %}

{% block body %}
    <div class="recherche">
        <h1>Tags</h1>
        <table class="table">
            <tr>
                <th>
                    Tag
                </th>
            </tr>
            {% for tag in tags %}
            <tr>
                <td>
                    <a href="{{ path('tag_show', {'id': tag.id}) }}">{{tag.name}} </a> 
                </td>
            <tr>
        {% endfor %}
        </table>
    </div>
{% endblock %}
      

templates/test.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index{% endblock %}


{% block body %}
	
	<div>
		<table class="table">
			<thead>
				<tr>
					<th>id</th>
					<th>Ville</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<th>1</th>
					<th>Olréans</th>
				</tr>
				<tr>
					<th>2</th>
					<th>Paris</th>
				</tr>
			</tbody>
		</table>
	</div>	
{% endblock %}